src/Entity/OpeningHours.php
<?php

namespace App\Entity;

use App\Repository\OpeningHoursRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OpeningHoursRepository::class)]
class OpeningHours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $blocOne = null;

    #[ORM\Column(length: 255)]
    private ?string $blocTwo = null;

    #[ORM\Column(length: 255)]
    private ?string $BlocThree = null;

    #[ORM\column(type: 'datetime_immutable', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;
//    #[ORM\Column]
//    private ?\DateTimeImmutable $created_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBlocOne(): ?string
    {
        return $this->blocOne;
    }

    public function setBlocOne(string $blocOne): self
    {
        $this->blocOne = $blocOne;

        return $this;
    }

    public function getBlocTwo(): ?string
    {
        return $this->blocTwo;
    }

    public function setBlocTwo(string $blocTwo): self
    {
        $this->blocTwo = $blocTwo;

        return $this;
    }

    public function getBlocThree(): ?string
    {
        return $this->BlocThree;
    }

    public function setBlocThree(string $BlocThree): self
    {
        $this->BlocThree = $BlocThree;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Découvrez l'univers culinaire du chef Arnaud Michant au Quai Antique, un restaurant situé à Chambéry et proposant une cuisine savoureuse inspirée des produits de la Savoie. Réservez votre table en ligne et vivez une expérience gastronomique inoubliable.">
    <meta name="author" content="Yoni-Alexandre Brault">
    <title> {% block title %}Le Quai Antique - Restaurant gastronomique {% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <!-- CSS local -->
    <link rel="stylesheet" href="{{ asset('assets/css/lequaiantique.css') }}">
    <!-- Carousel -->
    <link href="{{ asset('assets/css/carousel.css') }}" rel="stylesheet">
</head>
<body>

<!-- HEADER -->
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <a class="navbar-brand" href="{{ path('home')}}">Le Quai Antique</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('product_categories')}}">La Carte</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('menus')}}">Nos Menus</a>
                </li>
            </ul>
            <div class="navbar-item-custom">

            {# Si l'utilisateur est connecté #}
            {% if app.user %}
                <a href="{{ path('account') }}">Mon compte <small>({{ app.user.firstname }})</small></a> |||| <a href="{{ path('app_logout')}}">Déconnexion</a>
            {% else %}
                <a href="{{ path('app_login') }}">Connexion</a> |||| <a href="{{ path('app_register') }}">Inscription</a>
            {% endif %}

                <a href="{{ path('reservation') }}" > <button class="btn btn-info" type="button">Réserver</button></a>
            </div>
        </div>
    </nav>
</header>

<!-- CAROUSEL -->
<main role="main">
    {%  if block('carousel') is defined %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            {# Si la clé (key) est en position d'origine (0) alors la classe "active" devient active #}
            {% for key,header in headers %}
                <li data-target="#myCarousel" data-slide-to="{{ key }}" {% if key == 0 %}class="active"{% endif %}></li>
            {% endfor %}
        </ol>
        <div class="carousel-inner">
            {# Si la clé (key) est en position d'origine (0) alors la classe "active" devient active #}
            {% for key,header in headers %}
                <div class="carousel-image carousel-item {% if key == 0 %}active{% endif %}" style="background: url('uploads/images/{{ header.illustration }}');background-size: cover;">
                    <div class="container">
                        <div class="carousel-caption text-left">
                            <h1 class="carousel-h1">{{ header.name }}</h1>
                            <p class="carousel-p">{{ header.content }}</p>
                            <p><a class="carousel-p btn btn-lg btn-info" href="{{ header.btnUrl }}" role="button">{{ header.btnTitle }}</a></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {% endif %}

    <!-- Si le block carousel n'est pas défini alors je fais un Margin Top (mt-5) de 5 pixel dans la div-->
    <div class="container marketing {%  if block('carousel') is not defined %} mt-5 {% endif %}">

        {% block content %}
        {% endblock %}

    </div>

    <!-- FOOTER -->
    <div class="d-flex flex-column footer-custom">
        <div class="flex-grow-1"></div>
    <footer class="py-1">
        <div class="container">
            <div class="row justify-content-center text-center">
                <h3>Horaires</h3>
            </div>
            <div class="text-center">
                <i class="fas fa-clock fa-2x"></i>
            </div>
            <div class="row justify-content-center py-1">
            </div>

            {% for openingHour in openingHours %}
            <div class="row justify-content-center">
                <div class="col-md-3 text-center p-1 mb-1 bg-white rounded shadow">
                    <h4>Lundi</h4>
                    <p>{{ openingHour.blocOne }}</p>
                </div>
                <div class="col-md-3 text-center p-1 mb-1 bg-white rounded shadow">
                    <h4>Mar-Sam</h4>
                    <p>{{ openingHour.blocTwo }}</p>
                </div>
                <div class="col-md-3 text-center p-1 mb-1 bg-white rounded shadow">
                    <h4>Dimanche</h4>
                    <p>{{ openingHour.blocThree }}</p>
                </div>
            </div>
        {% endfor %}
            <div class="row justify-content-center text-center py-1">
                <p>Copyright &copy; 2023 - Yoni-Alexandre Brault</p>
            </div>
        </div>
    </footer>
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="{{ asset('assets/js/bootstrap.bundle.js') }}"></script>
{% block js %}
<script> src="{{ asset('assets/js/lequaiantique.js') }}" </script>
{% endblock %}
</body>
</html>